### ISSUE TITLE
inst/java directory should be cleaned before copying dependencies from java sub-module

### ISSUE THREAD

**Issue by marekhorst** [CeON/rJavaPackageExample#4]
I just realized `inst/java` may preserve unwanted artifacts after java dependencies changes when running `make`.

We do have `clean` task which can be executed explicitly but maybe we should specify it in `all` task to allow subsequnet `make` execution without bumping into problems?

**Comment by mkobos** [comment]
Good point. 

The simplest **solution of this particular problem** would be to remove `inst/java` directory before building subprojects (this way even if you run `make build` directly, you won't run into this problem), i.e. the main `Makefile` would look like something like this:

```
(...)
build-subprojects:
    rm -rf $(JAVA_BUILD_TARGET)
    mkdir $(JAVA_BUILD_TARGET)
    # The "readlink" command below returns absolute path to the directory.
    $(MAKE) -C $(SUBPROJECT_PATH_NUMBER_ADDER) build \
        BUILD_TARGET=$(shell readlink -f $(JAVA_BUILD_TARGET))
(...)
```

But I think that this issue uncovered a **wider problem**. Namely, what happens when there are two Java subprojects and they depend on different version of the same dependency. In such case, both jars corresponding to these dependencies would land in `inst/java`, say `jama-1.0.3.jar` and `jama-1.1.0.jar`. This would result in some difficult to localize problems when running the application.

The easiest solution of this wider problem would be to check, while copying the jars from a Java subproject to `inst/java` directory, if there are any jars corresponding to the same dependency but with different versions already there. If so, the build should fail. However, I suspect that implementing the code that checks if two jar files correspond to the same dependency but different versions might be non-trivial.

What do you think?

**Comment by marekhorst** [comment]
I guess we shouldn't reinvent the wheel and use maven instead to resolve such conflicts. In this scenario all java projects should have single uber project with disambiguated dependencies.

**Comment by mkobos** [comment]
Do you mean that all dependencies should be defined in the parent POM of all Java subprojects?

**Comment by marekhorst** [comment]
I've edited my comment and changed 'parent' - which may be misleading, to 'uber' ;) My initial thought was to have top project with other projects among dependencies - this way they would be disambiguated by maven on top project level.

**Comment by mkobos** [comment]
Ok. So if I understand correctly this idea:
- The top Java project would depend only on its subprojects. When running build of this top project, the Java subprojects would build and jars build in these subprojects would be copied to the `target` directory of the top Java project.
- The `rJavaPackageExample`'s main Makefile would reference only this top Java project and it wouldn't know anything about any other Java subprojects. While running `make build`, top project's build would be run and all the artifacts present in its `target` directory would be copied to `inst/java`.

Is that right?

**Comment by marekhorst** [comment]
Kind of. I was thinking of building top project and obtaining all its dependencies. Although I guess this would require listing all 'submodules' in uber module in order to build them automatically.

**Comment by mkobos** [comment]
I still don't have a clear vision how this solution would look like. Maybe I would obtain it while implementing it :) 

Anyway, since implementing this solution of the wider problem isn't trivial, I propose implementing solution of this particular problem as described in [one of the previous comments](https://github.com/CeON/rJavaPackageExample/issues/4#issuecomment-182401414) and adding the task of implementing the solution of the wider problem to the backlog. We can decide what to do with it when planning next iteration.

**Comment by marekhorst** [comment]
I can agree on adding this major task to backlog.

My idea was the following:
1. define parent module being reactor for all modules used by R by listing all modules explicitly in `<modules>` element. This way we could resolve dependency graph and build all our modules in right order with single goal.
2. among all modules we should define special one, let's call it `top` having all our other modules defined as dependencies
3. after running `mvn dependency:copy-dependencies` we should get resolved dependencies for `top` module and include them in R package

I guess this should work.

**Comment by mkobos** [comment]
I have never implemented this reactor approach myself but its sounds good.
